<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.27" />
    <PackageReference Include="MongoDB.Driver" Version="3.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

   <ItemGroup>
    <ProjectReference Include="..\..\Domain\P360.Evacuation.Domain\P360.Evacuation.Domain.csproj" />
    <ProjectReference Include="..\..\Repository\P360.Evacuation.Repository\P360.Evacuation.Repository.csproj" />
    <ProjectReference Include="..\..\..\..\Repository\P360.Repository\P360.Repository.csproj" />
  </ItemGroup>

</Project>
