<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.26" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Domain\A360.People.Domain\A360.People.Domain.csproj" />
    <ProjectReference Include="..\..\Repository\A360.People.Repository\A360.People.Repository.csproj" />
    <ProjectReference Include="..\..\..\..\Repository\A360.Repository\A360.Repository.csproj" />
    <ProjectReference Include="..\..\..\..\Email\A360.Email\A360.Email.csproj" />
  </ItemGroup>

</Project>
